First try according to the discussion on Issue #17.
Work needs to be done: we are missing the semicolon after the continue
(but not the identifier, if any). See current error:

JavaDecaf: Compiling file 'T.jdc'...
T.java:6: error: ';' expected
    continue someTag
                    ^
T.java:16: error: ';' expected
    continue
               ^
2 errors

Good news: we have all continues.
Bad news: we have missed all semicolons.

Will continue working on this asap. Now I must leave this computer.